language: node_js
node_js: node

branches:
  except:
    - master

script:
  - ./build.sh

after_success:
  - cd master
  - git remote add coding https://$CODING_USER:$CODING_KEY@git.coding.net/scaffrey/hosts.git
  - git push coding HEAD:master -f
